### ISSUE TITLE
Any thoughts on adding support for computed properties

### ISSUE THREAD

**Issue by tkrugg** [blueflag/graphql-aggregate#3]
Not sure how this could be implemented yet in the context of graphql, but say you have a model

```gql
User {
   name
   dateOfBirth
}
```
and you want to group users by age.

PS: nice job on this project!

**Comment by thepont** [comment]
Hey sorry for the late response but I think that should already work.

It will call the resolver for age and will therefor be able to resolve group by age.

```
User {
   name
   dateOfBirth
   age
}
```

where the age resolver negates the current year from the dob year
